source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Kuva' do
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'JWTDecode', '~> 2.0.0'
  pod 'KeychainSwift', '~> 7.0'
  pod 'AlamofireImage', '~> 3.1'
end
